// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9GtNJRd3p1VMi3FTjQofJphJesqkuM9g',
    appId: '1:558690982271:web:6ac5c74ef7484f1141224a',
    messagingSenderId: '558690982271',
    projectId: 'priyanshuu-yadavv',
    authDomain: 'priyanshuu-yadavv.firebaseapp.com',
    storageBucket: 'priyanshuu-yadavv.appspot.com',
    measurementId: 'G-DMGPF9HV52',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVMIhn7gweycMiE-KajNl_lQ05pdPDTyk',
    appId: '1:558690982271:android:738cd7a8aa8c8ea741224a',
    messagingSenderId: '558690982271',
    projectId: 'priyanshuu-yadavv',
    storageBucket: 'priyanshuu-yadavv.appspot.com',
  );
}
